#!/usr/bin/python3

import sys


def factorise(num):
    i = 2
    while i <= int(num / 2) + 1:
        if num % i == 0:
            p = int(num / i)
            print('{:d}={:d}*{:d}'.format(num, p, i))
            break
        else:
            i += 1


if __name__ == "__main__":
    f_name = sys.argv[1]
    with open(f_name, 'r') as f:
        for num in f:
            factorise(int(num))
